ZOTERO_LIBRARY_ID = "5650543"
ZOTERO_LIBRARY_TYPE = "group"

BABEL_DEFAULT_LOCALE = "en_US"
BABEL_DEFAULT_TIMEZONE = "Australia/Sydney"

SHOW_PROCESSING_TIME = false

# Most parameters have a default value. Deleting such parameter from this file
# will not disable it but merely reset it to its default value.

# Default to "metadata"
[kerko.scopes]

    [kerko.scopes.all]
    enabled = true
    weight = 0

    [kerko.scopes.creator]
    enabled = true
    weight = 100

    [kerko.scopes.title]
    enabled = true
    weight = 200

    [kerko.scopes.pubyear]
    enabled = true
    weight = 300

    [kerko.scopes.metadata]
    enabled = true
    weight = 400

    [kerko.scopes.fulltext]
    enabled = true
    weight = 500



[kerko.features]

download_attachment_new_window = false
download_item = true
download_results = true
download_results_max_count = 999
open_in_zotero_app = false
open_in_zotero_web = false
print_item = true
print_results = true
print_results_max_count = 0
relations_links = false
relations_initial_limit = 5
relations_sort = "author_asc"
results_abstracts = true
results_abstracts_max_length = 0
results_abstracts_max_length_leeway = 0
results_abstracts_toggler = false
results_attachment_links = false
results_url_links = true

[kerko.feeds]

formats = []
fields = ["id", "data"]
max_days = 0

[kerko.meta]

title = "PhDs.io"
google_analytics_id = "G-TFJCZ2EWMZ"

[kerko.pagination]

page_len = 12
pager_links = 5

[kerko.breadcrumb]

enabled = true
include_current = true
text_max_length = 50
text_max_length_leeway = 10

[kerko.link_groups]

[[kerko.link_groups.navbar]]
text = "Home"
type = "endpoint"
endpoint = "kerko.search"

[[kerko.link_groups.navbar]]
text = "Usage Guide"
type = "url"
url = "/usage"

[[kerko.link_groups.navbar]]
text = "About"
type = "url"
url = "/about"

[[kerko.link_groups.breadcrumb_base]]
text = "PhDs.io"
type = "url"
url = "/"

[kerko.performance]
whoosh_index_memory_limit = 1024
whoosh_index_processors = 1

[kerko.zotero]

# csl_style = "apa"
csl_style = "apa-no-doi-no-issue"
locale = "en-US"
item_include_re = ''
item_exclude_re = ''
# Indexing OA documents
child_include_re = '\[Open Access\]'
child_exclude_re = '^_'
attachment_mime_types = ["application/pdf"]
tag_include_re = '\[Topic\] (?P<kerko>.*)'
tag_exclude_re = '^_'

[kerko.search]

fulltext = true
whoosh_language = "en"


[kerko.facets]

[kerko.facets.for]
type = "tag_based_facet"
filter_key = "field-of-research"
title = "Field of Research"
enabled = true
weight = 40
initial_limit = 10
initial_limit_leeway = 2
sort_by = ["count"]
tag_include_re = '\[Field of Research\] (?P<kerko>.*)'
tag_exclude_re = "^_"

[kerko.facets.journals]
enabled = true
type = "collection"
collection_key = "ZT72UUC6"
filter_key = "journal"
title = "Journals"
weight = 50
initial_limit = 20
initial_limit_leeway = 2

[kerko.facets.year]
enabled = true
title = "Year"
weight = 70
initial_limit = 5
initial_limit_leeway = 2
sort_by = ["label"]

# This type is added to allow building facets based on tags
# Must set `tag_include_re` and `tag_exclude_re`
[kerko.facets.ranking]
type = "tag_based_facet"
filter_key = "ranking"
title = "Ranking"
enabled = true
weight = 90
initial_limit = 10
initial_limit_leeway = 2
sort_by = ["label"]
tag_include_re = '\[Ranking\] (?P<kerko>.*)'
tag_exclude_re = "^_"

[kerko.facets.open_access]
type = "tag_based_facet"
filter_key = "open-access"
title = "Open Access"
enabled = true
weight = 91
initial_limit = 10
initial_limit_leeway = 2
sort_by = ["label"]
tag_include_re = '\[(?P<kerko>Open Access)\]'
tag_exclude_re = "^_"

[kerko.facets.tag]
enabled = true
weight = 100
initial_limit = 20
initial_limit_leeway = 2
sort_by = ["label"]

[kerko.facets.item_type]
enabled = false

[kerko.templates]
base = "kerkoapp/base.html.jinja2"
layout = "kerkoapp/layout.html.jinja2"
item = "kerkoapp/item.html.jinja2"
search = "kerkoapp/search.html.jinja2"

# My own config
# These must be defined.
[custom]
show_macquarie_logo = false
# DO NOT DISPLAY PDF!!!
show_document = false
# Show Open Access, however.
show_open_access = true
open_access_tag = "[Open Access]"
# Ranking tags
ft50_tag = "[Ranking] FT50"
utd24_tag = "[Ranking] UTD24"
abdc_tag = "[Ranking] ABDC-A*" # Only tag A*
# Flash message / Announcement
show_flash_message = false
flash_message_path = "flash_message.txt"

[open_graph]
og_title = "PhDs.io - Knowledge that Transforms"
og_description = "Navigate high-quality research papers in finance, economics, accounting, and related fields. PhDs.io offers a simplified literature discovery experience."
